name: Build and Deploy NodeJS App on AWS
on:
  push:
    branches:
    - main
  
jobs:
  Build-App:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   
      - name: Barani CI/CD
        run:
          echo "Step 1"
      - name: Barani CI/CD
        run:
          echo "Step 2"

      - name: Barani CI/CD
        run:
          echo "Step 3"      

      - name: Barani CI/CD
        run:
          echo "Step 4"

      - name: Barani CI/CD
        run:
          echo "Step 5"      






          
